import express from 'express';
import { addProduct, listProducts, removeProduct, singleProduct } from '../controllers/productsController.js';
import upload from '../middleware/multer.js';
import adminAUth from '../middleware/adminAuth.js';
const productRouter = express.Router();
productRouter.post("/add", adminAUth, upload.fields([{ name: "image1", maxCount: 1 }, { name: "image2", maxCount: 1 }, { name: "image3", maxCount: 1 }, { name: "image4", maxCount: 1 }]), addProduct);
productRouter.post("/remove", adminAUth, removeProduct);
productRouter.get("/list", listProducts);
productRouter.post("/single", singleProduct);
export default productRouter;